server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/trackingdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: TRACKING-SERVICE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dev-budget-realm
          jwk-set-uri: http://localhost:8080/realms/dev-budget-realm/protocol/openid-connect/certs
