name: run unit test of new features

on:
  push:
    branches:
      'features/*'

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: run unit test
        run: mvn test
    
