name: Run Unit Tests for New Features

on:
  push:
    branches:
      - 'main' # Changed to '**' to correctly match branches under features/

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run unit tests
        run: mvn test
