name: Run Unit Tests for New Features

on:
  push:
    branches:
      - 'features/*'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: run unit test
        run: mvn test
    
