name: Run Unit Tests for New Features

on:
  push:
    branches:
      - 'main' # Changed to '**' to correctly match branches under features/

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21' # Matches the Java version specified in your pom.xml
          distribution: 'temurin' # AdoptOpenJDK is now Eclipse Temurin
          
      - name: Run unit tests
        run: mvn test
